<?php
/** @var $block \CepdTech\Regions\Block\Search */
/** @var $escaper \Magento\Framework\Escaper */

$apiKey = $escaper->escapeHtml($block->getApiKey());
$address = $block->getCustomerAddress();

?>
<div class="address-search__wrap">
    <div class="address-search__controls">
        <input name="address_search"
               type="text"
               class="address-search__input"
               placeholder="<?= __('Enter your shipping address') ?>"
               value="<?= $address ?>"
               data-mage-init='{"addressSearch": {}}'>
        <span class="address-search__clear" data-search="clear"></span>
    </div>
    <div class="address-search__error mage-error" generated="true" data-search="error"></div>
</div>

<div class="address-search__controls address-search__controls_modal" data-search="container">
    <input name="address_search" type="text" class="address-search__input" placeholder="<?= __('Enter your shipping address') ?>" data-mage-init='{"addressSearch": {}}'>
    <span class="address-search__clear" data-search="clear"></span>
    <div class="address-search__error mage-error" generated="true" data-search="error"></div>
</div>

<?php if ($apiKey) : ?>
    <script type="text/x-magento-init">
        {
            ".address-search__input": {
                "addressSearch": {
                    "country": "<?= $escaper->escapeHtml($block->getCountry()) ?>",
                    "apiKey": "<?= $apiKey ?>",
                    "addressData": "<?= $address ?>"
                }
            }
        }
    </script>
<?php endif ?>
